### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.0 für Windows Desktops
  description: Microsoft Application Virtualization Hosting 5.0 for Windows Desktops folgt der Fixed-Lifecycle-Richtlinie.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 640b1312c2eba7e693edbd82f34378619036195e
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935374"
name: Microsoft Application Virtualization Hosting 5.0 für Windows Desktops
summary: >+
  Microsoft Application Virtualization Hosting 5.0 for Windows Desktops folgt der [Fixed](/lifecycle/policies/fixed)-Lifecycle-Richtlinie.


  Dies gilt für die folgenden Editionen: for Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Service Pack 3
  startDate: 12/08/2014
  endDate: 04/14/2026
- version: Service Pack 2
  startDate: 11/08/2013
  endDate: 01/12/2016
- version: Service Pack 1
  startDate: 04/10/2013
  endDate: 01/13/2015
- version: Original Release
  startDate: 11/01/2012
  endDate: 07/08/2014
content: "\n## <a name=\"links\"></a>Links \n* [Produktinformationen](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Service Pack-Richtlinie](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Editionen \n* for Windows Desktops"
