### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 für Windows-Desktops
  description: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops folgt der Fixed-Lifecycle-Richtlinie.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 für Windows-Desktops
summary: |+
  Microsoft Application Virtualization Hosting 5.1 for Windows Desktops folgt der [Fixed](/lifecycle/policies/fixed)-Lifecycle-Richtlinie.

  Dies gilt für die folgenden Editionen: for Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Links 
  * [Produktinformationen](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Editionen 
  * for Windows Desktops