### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4,6
  description: Microsoft Application Virtualization 4,6 folgt der festen Lebenszyklusrichtlinie.
  ms.date: 07/28/2020
  ms.openlocfilehash: 868274b4468e663afe8e1b9f36069490ab4da025
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "817410"
name: Microsoft Application Virtualization 4,6
summary: >+
  Microsoft Application Virtualization 4,6 folgt der [festen](/lifecycle/policies/fixed) Lebenszyklusrichtlinie.


  Dies gilt für die folgenden Editionen: für Remote Desktop Dienste, für Windows-Desktops, Sequencer

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Links \n* [Produkt-und Migrationsinformationen](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Migrationsleitfaden](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Service Pack-Richtlinie](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Da der APP-v 4,6-Client den App-v 4,5-Server verwendet, wird der APP-v 4,5-Server weiterhin gemäß den Lebenszyklusdaten von App-v 4,6 unterstützt, wenn er mit dem unterstützten App-v 4,6-Client verwendet wird.\n\n## <a name=\"editions\"></a>Editionen \n* für Remote Desktop Dienste\n* für Windows-Desktops\n* Sequencer"
