### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security folgt der Fixed-Lifecycle-Richtlinie.
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113407"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security folgt der [Fixed](/lifecycle/policies/fixed)-Lifecycle-Richtlinie.


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Links \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security wurde am 14. Juli 2015 eingestellt. Antischadsoftware- und Antispyware-Definitionsupdates sind nach dem Ende der Unterst체tzung f체r die Produktversion nicht mehr verf체gbar. Bitte erw채gen Sie System Center Endpoint Protection als einen Ersatz."
