### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security folgt der Fixed-Lifecycle-Richtlinie.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security folgt der [Fixed](/lifecycle/policies/fixed)-Lifecycle-Richtlinie.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Links 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security wurde am 14. Juli 2015 eingestellt. Antischadsoftware- und Antispyware-Definitionsupdates sind nach dem Ende der Unterst체tzung f체r die Produktversion nicht mehr verf체gbar. Bitte erw채gen Sie System Center Endpoint Protection als einen Ersatz.